#! /usr/bin/env racket
#lang racket

(require racket/cmdline)
(require "utilities.rkt")
(require "compiler.rkt")

(debug-level 1)
(command-line 
  #:args (filename) ((compile-file #f compiler-passes) filename))
