(let ([a1 (read)])
  (+ a1 (let ([a2 (read)])
	  (+ a2 (let ([a3 (read)])
		  (+ a3 (let ([a4 (read)])
			  (+ a4 (let ([a5 (read)])
				  (+ a5 (let ([a6 (read)])
					  (+ a6 (let ([a7 (read)])
						  (+ a7 (let ([a8 (read)])
							  (+ a8 (let ([a9 (read)])
								  (+ a9 (let ([a10 (read)])
									  (+ a10 0))))))))))))))))))))
